In [5]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
import sys

def get_variable_size_gb(variable):
    size_bytes = sys.getsizeof(variable)
    return size_bytes / (1024 ** 3)

In [6]:
csv_to_read = "results/sana_results_0_1500_with_prediction_only_meaningful_results.csv"
df = pd.read_csv(csv_to_read, low_memory=False)

In [9]:
df

,mrna_start,mrna_end,mrna_dot_bracket_5to3,mirna_start,mirna_end,mirna_dot_bracket_5to3,pred_energy,mirna_accession,mrna_sequence,mirna_sequence,is_mutated,id,chr,start_coordinate,end_coordinate,alignment_string,pred_num_basepairs,pred_seed_basepairs,ta_log10,sps_mean,mre_end,mre_start,mre_region,anchor_a,6mer_seed,match_8,6mer_seed_1_mismatch,compensatory_site,supplementary_site,supplementary_site_2,empty_seed,9_consecutive_match_anywhere,mirna_conservation,seed_8mer,seed_7mer_a1,seed_7mer_m8,seed_compensatory,seed_clash_2,seed_clash_3,seed_clash_4,seed_clash_5,mre_au_content,local_au_content,prediction,binary_prediction,pred_difference,pred_difference_binary
0,30,36,.((((.,8,14,.)))).,-4.0,MIMAT0000062,GTTTTTGATTCCTAATTCAATCTCTTGTTACAGGTCTATTCAGATT...,AACTATACAACCTACTACCTCA,0,10_102293465_C_T_MIMAT0000062,10,102293465,102293471,000000000111100000000,4,0,3.346,-4.312,44,22,TCTTGTTACAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.636364,0.688525,0.002044,0,0.901743,1
1,25,36,.((..(((((.,8,19,.)))))..)).,-6.3,MIMAT0000062,GTTTTTGATTCCTAATTCAATCTCTTGTTATAGGTCTATTCAGATT...,AACTATACAACCTACTACCTCA,1,10_102293465_C_T_MIMAT0000062,10,102293460,102293471,000000000111110011000,7,0,3.346,-4.312,44,22,TCTTGTTATAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.681818,0.704918,0.903786,1,0.901743,1
2,30,36,.((((.,8,14,.)))).,-4.0,MIMAT0000063,GTTTTTGATTCCTAATTCAATCTCTTGTTACAGGTCTATTCAGATT...,AACCACACAACCTACTACCTCA,0,10_102293465_C_T_MIMAT0000063,10,102293465,102293471,000000000111100000000,4,0,3.524,-8.679,44,22,TCTTGTTACAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.636364,0.688525,0.106618,0,0.873252,1
3,25,36,.((..(((((.,8,19,.)))))..)).,-6.3,MIMAT0000063,GTTTTTGATTCCTAATTCAATCTCTTGTTATAGGTCTATTCAGATT...,AACCACACAACCTACTACCTCA,1,10_102293465_C_T_MIMAT0000063,10,102293460,102293471,000000000111110011000,7,0,3.524,-8.679,44,22,TCTTGTTATAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.681818,0.704918,0.979870,1,0.873252,1
4,30,36,.((((.,8,14,.)))).,-4.0,MIMAT0000064,GTTTTTGATTCCTAATTCAATCTCTTGTTACAGGTCTATTCAGATT...,AACCATACAACCTACTACCTCA,0,10_102293465_C_T_MIMAT0000064,10,102293465,102293471,000000000111100000000,4,0,3.266,-6.285,44,22,TCTTGTTACAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.636364,0.688525,0.000376,0,0.770978,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472689,17,34,.((((((..(((((((.,3,18,.))))))))))))).,-12.6,MIMAT0049023,CAATTAAATTTTATGAACATTGAAATTTGGGTTTCATATAATTTTC...,GTCTGACCCAGTTCAGTACATC,1,X_88181906_A_G_MIMAT0049023,X,88181893,88181910,000011111111111110000,13,3,3.420,-8.292,37,15,AACATTGAAATTTGGGTTTCAT,0,0,1,0,1,1,0,0,1,-1.0,0,0,0,0,0,0,0,1,0.727273,0.770492,0.817556,1,0.750502,1
472690,48,56,.(((.((.,7,15,.)).))).,-4.1,MIMAT0049024,CAATTAAATTTTATGAACATTGAAATTTGGATTTCATATAATTTTC...,GCAAAAAAGGTACAACCCG,0,X_88181906_A_G_MIMAT0049024,X,88181924,88181932,000000001101110000,5,0,4.088,-1.965,63,44,TCATGTGTTCCAAAATG,0,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.647059,0.786885,0.051589,0,0.918929,1
472691,27,56,.((((.................(((.((.,7,19,.)).))))))).,-7.6,MIMAT0049024,CAATTAAATTTTATGAACATTGAAATTTGGGTTTCATATAATTTTC...,GCAAAAAAGGTACAACCCG,1,X_88181906_A_G_MIMAT0049024,X,88181903,88181932,0000000011011111110,9,0,4.088,-1.965,63,44,TCATGTGTTCCAAAATG,0,0,0,0,1,1,0,1,0,2.0,0,0,0,0,0,0,0,0,0.647059,0.770492,0.970518,1,0.918929,1
472692,15,33,.((..(((((((..(((.,0,19,.)))..)))).)))..)).,-4.7,MIMAT0049026,CAATTAAATTTTATGAACATTGAAATTTGGATTTCATATAATTTTC...,CATCATAATTCTCACAGTAATA,0,X_88181906_A_G_MIMAT0049026,X,88181891,88181909,011100111101110011000,12,4,3.466,-3.626,33,11,TATGAACATTGAAATTTGGATT,0,0,1,0,0,0,0,0,0,2.0,0,0,0,0,0,0,0,1,0.772727,0.786885,0.949728,1,-0.707982,-1
472693,9,17,.((((((.,1,9,.)))))).,-4.3,MIMAT0049026,CAATTAAATTTTATGAACATTGAAATTTGGGTTTCATATAATTTTC...,CATCATAATTCTCACAGTAATA,1,X_88181906_A_G_MIMAT0049026,X,88181885,88181893,001111110000000000000,6,5,3.466,-3.626,18,0,CAATTAAATTTTATGAAC,0,0,1,1,0,0,0,0,0,2.0,0,0,0,0,0,0,0,0,0.833333,0.770492,0.241746,0,-0.707982,-1

In [2]:
file_path = "results/PD3851a_case_1.csv"
file_name = file_path.split("/")[1].split("_")[0]

print(file_name)

PD3851a

In [7]:
df.head()

,mrna_start,mrna_end,mrna_dot_bracket_5to3,mirna_start,mirna_end,mirna_dot_bracket_5to3,pred_energy,mirna_accession,mrna_sequence,mirna_sequence,is_mutated,id,chr,start_coordinate,end_coordinate,alignment_string,pred_num_basepairs,pred_seed_basepairs,ta_log10,sps_mean,mre_end,mre_start,mre_region,anchor_a,6mer_seed,match_8,6mer_seed_1_mismatch,compensatory_site,supplementary_site,supplementary_site_2,empty_seed,9_consecutive_match_anywhere,mirna_conservation,seed_8mer,seed_7mer_a1,seed_7mer_m8,seed_compensatory,seed_clash_2,seed_clash_3,seed_clash_4,seed_clash_5,mre_au_content,local_au_content,prediction,binary_prediction,pred_difference,pred_difference_binary
0,30,36,.((((.,8,14,.)))).,-4.0,MIMAT0000062,GTTTTTGATTCCTAATTCAATCTCTTGTTACAGGTCTATTCAGATT...,AACTATACAACCTACTACCTCA,0,10_102293465_C_T_MIMAT0000062,10,102293465,102293471,000000000111100000000,4,0,3.346,-4.312,44,22,TCTTGTTACAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.636364,0.688525,0.002044,0,0.901743,1
1,25,36,.((..(((((.,8,19,.)))))..)).,-6.3,MIMAT0000062,GTTTTTGATTCCTAATTCAATCTCTTGTTATAGGTCTATTCAGATT...,AACTATACAACCTACTACCTCA,1,10_102293465_C_T_MIMAT0000062,10,102293460,102293471,000000000111110011000,7,0,3.346,-4.312,44,22,TCTTGTTATAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.681818,0.704918,0.903786,1,0.901743,1
2,30,36,.((((.,8,14,.)))).,-4.0,MIMAT0000063,GTTTTTGATTCCTAATTCAATCTCTTGTTACAGGTCTATTCAGATT...,AACCACACAACCTACTACCTCA,0,10_102293465_C_T_MIMAT0000063,10,102293465,102293471,000000000111100000000,4,0,3.524,-8.679,44,22,TCTTGTTACAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.636364,0.688525,0.106618,0,0.873252,1
3,25,36,.((..(((((.,8,19,.)))))..)).,-6.3,MIMAT0000063,GTTTTTGATTCCTAATTCAATCTCTTGTTATAGGTCTATTCAGATT...,AACCACACAACCTACTACCTCA,1,10_102293465_C_T_MIMAT0000063,10,102293460,102293471,000000000111110011000,7,0,3.524,-8.679,44,22,TCTTGTTATAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.681818,0.704918,0.979870,1,0.873252,1
4,30,36,.((((.,8,14,.)))).,-4.0,MIMAT0000064,GTTTTTGATTCCTAATTCAATCTCTTGTTACAGGTCTATTCAGATT...,AACCATACAACCTACTACCTCA,0,10_102293465_C_T_MIMAT0000064,10,102293465,102293471,000000000111100000000,4,0,3.266,-6.285,44,22,TCTTGTTACAGGTCTATTCAGA,1,0,0,0,0,0,0,1,0,2.0,0,0,0,0,0,0,0,0,0.636364,0.688525,0.000376,0,0.770978,1